# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Exome solo négatif
  - trigger: ":esneg"
    replace: "Dans la limite des connaissances actuelles et des techniques utilisées, l’analyse de l'exome en solo n’a pas permis l’identification d’une variation de séquence pouvant expliquer le phénotype selon les informations cliniques transmises. Un résultat négatif n’exclut pas la possibilité d’une maladie génétique."
    
  # Exome duo négatif
  - trigger: ":edneg"
    replace: "Dans la limite des connaissances actuelles et des techniques utilisées, l’analyse de l'exome en duo (cas index et mère/père) n’a pas permis l’identification d’une variation de séquence pouvant expliquer le phénotype selon les informations cliniques transmises. Un résultat négatif n’exclut pas la possibilité d’une maladie génétique."
     
  # Exome trio négatif
  - trigger: ":etneg"
    replace: "Dans la limite des connaissances actuelles et des techniques utilisées, l’analyse de l'exome en trio (cas index et parents) n’a pas permis l’identification d’une variation de séquence pouvant expliquer le phénotype selon les informations cliniques transmises. Un résultat négatif n’exclut pas la possibilité d’une maladie génétique."

  # Génome solo négatif
  - trigger: ":gsneg"
    replace: "Dans la limite des connaissances actuelles et des techniques utilisées, l’analyse du génome en solo n’a pas permis l’identification d’une variation génomique pouvant expliquer le phénotype selon les informations cliniques transmises. Un résultat négatif n’exclut pas la possibilité d’une maladie génétique."
    
  # Génome duo négatif
  - trigger: ":gdneg"
    replace: "Dans la limite des connaissances actuelles et des techniques utilisées, l’analyse du génome en duo (cas index et mère/père) n’a pas permis l’identification d’une variation génomique pouvant expliquer le phénotype selon les informations cliniques transmises. Un résultat négatif n’exclut pas la possibilité d’une maladie génétique."
     
  # Génome trio négatif
  - trigger: ":gtneg"
    replace: "Dans la limite des connaissances actuelles et des techniques utilisées, l’analyse du génome en trio (cas index et parents) n’a pas permis l’identification d’une variation génomique pouvant expliquer le phénotype selon les informations cliniques transmises. Un résultat négatif n’exclut pas la possibilité d’une maladie génétique."
    
  # Examen exome
  # Remplacer hétérozygote par homozygote au besoin
  - trigger: "ethc"
    replace: "L'examen des données d'exome en trio (cas index et parents) a mené à l'identification de deux variations à l'état hétérozygote composite dans le gène."
    
  - trigger: ":etFS"
    replace: "L'examen des données d'exome en trio (cas index et parents) a mené à l'identification d'une variation faux-sens à l'état hétérozygote dans le gène."
    
  - trigger: ":esFS"
    replace: "L'examen des données d'exome du cas index a mené à l'identification d'une variation faux-sens à l'état hétérozygote dans le gène."
    
  - trigger: ":etns"
    replace: "L'examen des données d'exome en trio (cas index et parents) a mené à l'identification d'une variation non-sens à l'état hétérozygote dans le gène."
    
  - trigger: ":esns"
    replace: "L'examen des données d'exome du cas index a mené à l'identification d'une variation non-sens à l'état hétérozygote dans le gène."
    
  - trigger: ":etdelins"
    replace: "L'examen des données d'exome en trio (cas index et parents) a mené à l'identification d'une delins en phase à l'état hétérozygote dans le gène."
    
  - trigger: ":esdelins"
    replace: "L'examen des données d'exome du cas index a mené à l'identification d'une delins en phase à l'état hétérozygote dans le gène."
    
  - trigger: "etsplice"
    replace: "L'examen des données d'exome en trio (cas index et parents) a mené à l'identification d'une substitution nucléotidique à l'état hétérozygote dans l'exon/intron du gène."
    
  - trigger: "essplice"
    replace: "L'examen des données d'exome en solo a mené à l'identification d'une substitution nucléotidique à l'état hétérozygote dans l'exon/intron du gène."

  # Examen génome
  # Remplacer hétérozygote par homozygote au besoin
  - trigger: "gthc"
    replace: "L'examen des données de génome en trio (cas index et parents) a mené à l'identification de deux variations à l'état hétérozygote composite dans le gène."
    
  - trigger: ":gsFS"
    replace: "L'examen des données de génome du cas index a mené à l'identification d'une variation faux-sens à l'état hétérozygote dans le gène."
    
  - trigger: ":gdFS"
    replace: "L'examen des données de génome en duo (cas index et père/mère) a mené à l'identification d'une variation faux-sens à l'état hétérozygote dans le gène."
    
  - trigger: ":gtFS"
    replace: "L'examen des données de génome en trio (cas index et parents) a mené à l'identification d'une variation faux-sens à l'état hétérozygote dans le gène."
    
  - trigger: ":gqFS"
    replace: "L'examen des données de génome en quatuor (cas index, parents et frère/sœur) a mené à l'identification d'une variation faux-sens à l'état hétérozygote dans le gène."
    
  - trigger: ":gsns"
    replace: "L'examen des données de génome du cas index a mené à l'identification d'une variation non-sens à l'état hétérozygote dans le gène."

  - trigger: ":gdns"
    replace: "L'examen des données de génome en duo (cas index et père/mère) a mené à l'identification d'une variation non-sens à l'état hétérozygote dans le gène."

  - trigger: ":gtns"
    replace: "L'examen des données de génome en trio (cas index et parents) a mené à l'identification d'une variation non-sens à l'état hétérozygote dans le gène."
    
  - trigger: ":gqns"
    replace: "L'examen des données de génome en quatuor (cas index, parents et frère/sœur) a mené à l'identification d'une variation non-sens à l'état hétérozygote dans le gène."
    
  - trigger: ":gsdelins"
    replace: "L'examen des données de génome du cas index a mené à l'identification d'une delins en phase à l'état hétérozygote dans le gène."
    
  - trigger: ":gtdelins"
    replace: "L'examen des données de génome en duo (cas index et père/mère) a mené à l'identification d'une delins en phase à l'état hétérozygote dans le gène."

  - trigger: ":gtdelins"
    replace: "L'examen des données de génome en trio (cas index et parents) a mené à l'identification d'une delins en phase à l'état hétérozygote dans le gène."
    
  - trigger: ":gqdelins"
    replace: "L'examen des données de génome en quatuor (cas index, parents et frère/sœur) a mené à l'identification d'une delins à l'état hétérozygote dans le gène."
  
  # Inheritance
  - trigger: ":dn"
    replace: "La variation est survenue de novo."
    
  - trigger: ":hm"
    replace: "La variation est présente chez la mère à l'état hétérozygote."
    
  - trigger: ":hp"
    replace: "La variation est présente chez le père à l'état hétérozygote."
    
  - trigger: ":nhm"
    replace: "La variation n'est pas détectée chez la mère."

  - trigger: ":nhp"
    replace: "La variation n'est pas détectée chez le père."
    
  - triffer: ":hd"
    replace: "La variation est présente chez chacun des parents à l'état hétérozygote."
    
  # gnomAD    
  - trigger: ":agnom"
    replace: "La variation est absente de la base de données gnomAD v4.1.0."
    
  - trigger: ":pgnom"
    replace: "La variation est présente dans la base de données gnomAD v4.1.0."
  
  # Conservation et domaine

  - trigger: ":tcons"
    replace: "Elle touche un acide aminé très conservé au cours de l'évolution, "

  - trigger: ":cons"
    replace: "Elle touche un acide aminé relativement conservé au cours de l'évolution, "
    
  - trigger: ":mcons"
    replace: "Elle touche un acide aminé moyennement conservé au cours de l'évolution, "
  
  - trigger: ":ddom"
    replace: "localisé dans le domaine."
  
  - trigger: ":hdom"
    replace: "non localisé dans un domaine protéique fonctionnel connu."
    
  # Prédiction in silico    
  - trigger: ":dpred"
    replace: "Les outils de prédiction in silico sont en faveur du caractère délétère de la variation."
    
  - trigger: ":bpred"
    replace: "Les outils de prédiction in silico sont discordants quant au caractère délétère de la variation."
    
  - trigger: ":intol"
    replace: "Le gène est intolérant aux variations perte de fonction (LOEUF à , gnomAD v4.1.0)."
    
  - trigger: ":predsplice"
    replace: "Les scores de prédiction in silico prédisent un effet délétère sur l’épissage avec une altération très probable du site accepteur/donneur de l'intron/exon."
 
  # ClinVar
  # Au besoin, associer les phénotypes associés
  - trigger: ":cv3"
    replace: "La variation est rapportée dans la base de données ClinVar comme étant de signification incertaine."

  - trigger: ":cv4"
    replace: "La variation est rapportée dans la base de données ClinVar comme étant probablement pathogène."

  - trigger: ":cv5"
    replace: "La variation est rapportée dans la base de données ClinVar comme étant pathogène."

  - trigger: ":lovd4"
    replace: "La variation est rapportée dans LOVD comme étant probablement pathogène."

  - trigger: ":lovd5"
    replace: "La variation est rapportée dans LOVD comme étant pathogène."
    
  - trigger: ":cvtemper"
    replace: "Cependant la soumission n'est pas accompagnée de publications scientifiques pouvant supporter la pathogénicité de la variation par des tests fonctionnels."
  
  # littérature
  
  
  # OMIM
  - trigger: ":ad"
    replace: "Les variations monoalléliques pathogènes du gène sont impliquées dans (OMIM #) de transmission autosomique dominante."
    
  - trigger: ":ar"
    replace: "Les variations bialléliques pathogènes du gène sont impliquées dans (OMIM #) de transmission autosomique récessive."
    
  - trigger: ":rlx"
    replace: "Les variations pathogènes monoalléliques chez les hommes et bialléliques chez les femmes du gène sont impliquées dans (OMIM #) de transmission récessive liée à l'X."
    
  - trigger: ":dlx"
    replace: "Les variations monoalléliques pathogènes du gène sont impliquées dans (OMIM #) de transmission dominante liée à l'X."

  # Clinique
  - trigger: ":clinic"
    replace: "Les signes cliniques observés sont compatibles avec cette pathologie."
    
  # Conclusion
  - trigger: ":c3"
    replace: "En l'état actuel des connaissances et des techniques, la variation de séquence est considérée comme étant de signification incertaine."
 
  - trigger: ":c4"
    replace: "En l'état actuel des connaissances et des techniques, cette variation de séquence probablement pathogène est considérée comme la cause probable de la symptomatologie observée."

  - trigger: ":p4"
    replace: "En l’état actuel des connaissances et des techniques, cette variation de séquence probablement pathogène est considérée comme la cause probable d'une partie du phénotype observé."

  - trigger: ":c5"
    replace: "En l'état actuel des connaissances et des techniques, cette variation de séquence pathogène est considérée comme la cause de la symptomatologie."
    
  - trigger: ":p5"
    replace: "En l’état actuel des connaissances et des techniques, cette variation de séquence pathogène est considérée comme la cause d'une partie du phénotype observé."
    
  - trigger: ":génotypec3"
    replace: "En l'état actuel des connaissances et des techniques, le génotype associant ces deux variations de séquence est considéré comme étant de signification incertaine."
    
  - trigger: ":génotypec4"
    replace: "En l'état actuel des connaissances et des techniques, le génotype associant ces deux variations de séquence est considéré comme étant probablement pathogène."

  - trigger: ":génotypec5"
    replace: "En l'état actuel des connaissances et des techniques, le génotype associant ces deux variations de séquence est considéré comme étant pathogène."

    # Données incidentes
  - trigger: ":dic4"
    replace: "En l'état actuel des connaissances et des techniques, cette variation de séquence est considérée comme probablement pathogène. S'agissant d'un diagnostic présymptomatique, ce résultat doit être confirmé sur un second échantillon biologique indépendant par un laboratoire expert. Une consultation spécialisée est nécessaire pour une prise en charge adaptée."
    
  - trigger: ":dic5"
    replace: "En l'état actuel des connaissances et des techniques, cette variation de séquence est considérée comme pathogène. S'agissant d'un diagnostic présymptomatique, ce résultat doit être confirmé sur un second échantillon biologique indépendant par un laboratoire expert. Une consultation spécialisée est nécessaire pour une prise en charge adaptée."
    
  # Confirmation
  - trigger: ":conf"
    replace: "sous réserve de confirmation par séquençage de Sanger ciblé."

  # Explorations (ségrégation, rétrophénotypage, étude d'épissage)
  - trigger: ":segreg"
    replace: "Une étude de la ségrégation familiale associée à un phénotypage des membres pourrait éventuellement permettre de progresser dans la classification de cette variation."
  
  - trigger: ":rpci"
    replace: "Un rétrophénotypage pourrait permettre de mieux évaluer l’implication éventuelle de cette variation dans le phénotype."
    
  - trigger: ":rpm"
    replace: "Un rétrophénotypage de la mère pourrait permettre de mieux évaluer l’implication éventuelle de cette variation dans le phénotype."
    
  - trigger: ":rpp"
    replace: "Un rétrophénotypage du père pourrait permettre de mieux évaluer l’implication éventuelle de cette variation dans le phénotype."
    
  - trigger: ":épidiag"
    replace: "Une étude de la méthylation via EpiSign est possible pour les variations du gène. Elle pourrait permettre de progresser dans l'interprétation de cette variation."
      
  - trigger: ":épirech"
    replace: "Une étude de la méthylation de l'ADN, dans le cadre de la recherche, pourrait permettre de mieux évaluer l'implication de cette variation dans le phénotype."
    
  - trigger: ":ARN"
    replace: "Une analyse d’épissage sur ARN extrait d’un échantillon sanguin sur tube PAXgene pourrait contribuer à mieux comprendre l’implication éventuelle de cette variation dans la pathologie observée."
    
  #Une étude de méthylation, dans le cadre de la recherche, pourrait également permettre de confirmer ou non l’implication de cette variation en pathologie humaine et éventuellement de stratifier les variations dans ce gène selon la sévérité du phénotype des sujets atteints.
  
  # Surveillance
  - trigger: ":neuroped"
    replace: "Une consultation en neuropédiatrie est recommandée, afin de dépister une éventuelle épilepsie et de mettre en place un suivi neurologique adapté."
    
  # Variation hétérozygote pour une maladie récessive  
  - trigger: ":hetrec"
    replace: "En l’état actuel des connaissances et des techniques, il s’agit d’une variation (probablement) pathogène pour une maladie de transmission autosomique récessive, insuffisante à elle seule à l’état hétérozygote pour être rapportée comme étant en lien avec la maladie.
    Un rétrophénotypage avec une confrontation des descriptions de la littérature ainsi que la réalisation d’un séquençage de génome à la recherche d’une éventuelle seconde variation (non détectable par l'exome) dans le gène X pourrait éventuellement permettre de progresser dans l'identification d'une cause moléculaire de la pathologie."
  
  
  # Dépistage néonatal
  - trigger: ":ddn"
    replace: "Le dépistage néonatal génomique par analyse d’un panel de gènes in silico (listes 1 et 2) en solo a mené à l'identification d'une variation hétérozygote de type X dans le gène X."
  
  # Présymptomatique
  - trigger: ":dsp1"
    replace: "Absence de la variation de séquence dans le gène. Ce résultat doit être confirmé sur un second prélèvement sanguin indépendant."
    
  - trigger: ":dps2"
    replace: "Absence de la variation de séquence dans le gène. Ce résultat confirme celui obtenu sur le premier prélèvement sanguin."
  
  # Faux positif
  - trigger: ":fp"
    replace: "Les données observées suggèrent la possibilité d’un faux positif. Il est indispensable de confirmer la présence de cette variation par une technique alternative. Si la présence de la variation est confirmée, elle est à considérer comme étant la cause de la pathologie."
    
  # Recherche
  - trigger: ":rech"
    replace: "L’analyse de génome réalisée chez X, né le X, a mené à l’identification d’une variation de signification incertaine dans le cadre de la recherche."
    
  - trigger: ":nonomim"
    replace: "Le gène n’est actuellement pas rapporté comme étant morbide dans la base de données OMIM."
    
  - trigger: ":gm"
    replace: "Un partage de la variation sur la plateforme GeneMatcher est réalisé et pourrait permettre de mieux caractériser les pathologies associées au gène et éventuellement de progresser dans la classification de la variation."
    
  - trigger: ":étude"
    replace: "Une étude menée par le Dr X est en cours pour mieux caractériser les pathologies associées au gène."
